language: scala
scala: 2.12.10
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "yN+xsaPl6jiltkya6AwvbLc8lXeJW5yS3cvHMYJtenEg7Wi0rq9uPfLDr/8plkZfv5DUBOLldlUjYDSGzCTgjfZiPpMhAyfrKNnQF1wEoJNfDlIpmecQaKgt5FS3VYZsC4l4+7UN56YVoymZbrsi2dOjiO9u2WundizttYLPcc22IV3t46dF0RQnk1HC3cykVdGeTKpgbX3hPqiFpmYBeN1yHNUm7xJrt08azEggy5cVg5DvOXPOStQUnO7to/G6uEATxojeoFUjoSN0EcJGLHVOL81DAmTGgmr1VFk/RRzk77Qjw6Fyhkp/ufeQ6UGQeIee29WETw7f57OgpGxySD7St/XRCR3gHz+MzFbiJWSuIkcAxwEyD+9HAIuCgtcC1o8MOwbQyuesLw1uqRvPvXh0rytsaeIK6FxmgTmAE5unnXKmydD2SRBkq6O/hB3nKo4oVwsduFLoTjklFJEqbgGAQ4jwkF95I+Ed9xoSgTmf8zGEi8WnStWUkBL5OnA1HCmJxArH4fA4z+23Y8RrLy7NNzA2ejZ7QI3hD0KT2hXh6foEw/wEAqE2DveAOfFst7f5cW1LL95sgxRjiWVeq17Az3hL3Tnp75Z2nSjnbBYqt31Xh7fk5XdOOijiddhjmiOChTx3mrj11k8QWCkwGdXiM9Y3CC0WiuQ6Ur2oSyg="
    # GITHUB_TOKEN
    - secure: "exVM96KWHy3+ztlBE1d9Lo/1Rpxsg500FuaovZ3/ZU1q6UdGOOb3onTPwb1Dj1kHHPDloZbFu/2tTJ0PPLIcSARg7sUjI/oZbXqdfemw4pBXN5Xq/NiUb06ORu+Rg3qq9Ib0rMPtyKhcXO+0hSmfLfWOBpGQA1IznBZyOqpp9jYTpEuqmsJaWxy8rdH0L9cYMPkrcZhZ9Bi640TIzhhcroBx6N+DcEV6cmsPItwKx6kRSv0yTBGU5yiBmKhcE05EPIESkhYNWrjxwzzwBAQJMJy3XfPlLzig32bZsNYrjsVKuYgOqBNo4pGS2qJO3OfutGKTgQkzoVKAx/zUei+bWDt9q04pQJYCY9UBkHOU60kqy5cd1ivf5OC4hHb7e+qUZOrtxQ0OXk0lzgBUkGtuZnKOXHEznwCYgv1lKV1KY/wa/AD3IUNnW1XTIVsx7KluhCkFVBUldpn30kzbKUyZPrP5fYmNGVmLFHvGOwokmaliFOkddYb/2ESyP36Avq5dQ8XVvhqKjB3YpMXEZbgTPZBTrw2X/48A5VfxNSNs1vV3hG3EI6iiORlcelzz5njHvUkWqLA0N2TdJACV5NByOfxlXcAcq5frixdRmwyC9XeadmwedlZF/KvRjdQw5DCWsa80FOc92dg5f236IyK7o3o8s5TSAA0R9gF8Qncqj3A="
    # GITHUB_ACCESS_TOKEN
    - secure: "ehE9mKr48EgEfHea3KcBIPdEqud26lUh1krfpHhQs092jmcWDS7WUbYKY657GVGFzyf7N4Fz1G2Ox700F4XhiQrv4/Y85wWTOuJ48jcmTzsHbtD9vIGa6vwPMnMiYYpbLZbNZdkvcehZh0ErQ9rrH+zAgpmIAj3/+Hg1EYDxA+Gg+2RhCHF0A1Lxx7he9a+axfb5mdwrPqx1ay5v3rImP1GkWfeSk5yf+4A2/2OYAO4ldgY7fscYg3Yx/kBBKH/1/6m5TcRlJMI9YWvZ20HmdptPx4E9R+ZvSN1ft99wpM0JK/b5bxf3mos1Hi8p6t+87jB/hJ8ZDkqYo/u3fn8yaQD0BhUMrx6IRZQnAMKJgY9TCohp1xbOmPkBmrNi7md0RTH5SYP9hnwZXH4ED+jErTczJ9yy03JoUGpdvN3F1XhpuDVBiiszP9m89fRvarKwtjP5Hw6EZ3S95iNbe/3X3ig59eNHh5fbspVm8DnMiHS4ZYfePf33rr6wTUa1VcUEeDWcsgXaCtceYmMH6qSEqfB6x/CHQI7nfCraSQaHbdUcUkyRbZb6Do5Jp+vAx3y8f23+DbzjZ0KL5WCMdllbuX1roeo8b4FD//hLwinABeeFcMnb9ejpmmB0ivyVx1MnQ6JcRHLXwfkwAmHa1ftyukZeTxobcWW1D7Kd6+EcXJA="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "1oQVioaLbuz+j1+6m9oGphEnMwl4Oyu5EcpAmtPbx4vajvBji3PwBR+GOzo89/qubrotQf78wGBNJxHP+nt0cc1TITiSzLUCJcxoMWCjzTumXxeuufDmxxlpwidx1IDymJTv0Ue/Df6KLWhQx2PNaUVnJZtZ2x6J0gNlJtpF2RozeQNKr0rmHg1b6OVLbypshIp3QaEIpNZzKUdNtuFV3VEilfs1qemyykoWuJcT0sha7PmIy9O6wi+mprVPWTciI8WAMf5eiFqc6Ap6QNChjTKY1ahwzNCsceKnOkJhR7x9uHTWJeHCFTij/qJTFpTvpGhJdMtm7tYDXTdG/HO8jyA9PAaHJ0vQgXLp+l9Pq5isHEm0+AEM/jCr5V5Eaqik/sqIFko+RJBCrulFCTCCm299rtKjjPYqxQpAD8NCo26y2C3WOOwMfR7cNX5hgZAGGDzka6ajCy2Hy8abR0vRfKWYvJQJJSMnrYVRhY2dfm1CGECXtJJbTbxoESGlGN90fpjZzOi5aBw8E/+Ktmh/GQlEZaHRqTf+3afobjAzp7fAhO4bJ+UOWjmDQNpJpHA5/07VO1WNRKmQpAQySmx3iS2QE7gxzc0rOYIPBYmh678fz6ZGBTOUb1eefM5rfzWTzRE8PN3vLMVQVpqprFUbo6t6sZnhpbkkuOg2yQ5IOTA="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/quasar-destination-azure';
        bumpInDownstream() { echo $1 > slamdata-destination-azure-version; }
        export -f bumpInDownstream
        scripts/bumpDependentProject slamdata slamx bumpInDownstream
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
